wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1735183282.0
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      2:
      - 1
      - 9
      - 50
      - 55
      3:
      - 1
      - 7
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
generator:
  desc: null
  value: null
discriminator:
  desc: null
  value: null
z_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0002
wd:
  desc: null
  value: 0.0
